import{a as h,i as P,S as q}from"./assets/vendor-527658dd.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const y=15;h.defaults.baseURL="https://pixabay.com/api/";const E="42471453-a4a004408e33f852748a0909e";async function L(r,s){const o="photo",i="horizontal",{data:t}=await h.get("",{params:{page:r,per_page:y,key:E,q:s,image_type:o,orientation:i,safesearch:!0}});return t}function v(r,s){const o=r.map(({webformatURL:i,largeImageURL:e,tags:t,likes:n,views:b,comments:w,downloads:I})=>`<li class="image-search">
        <a href="${e}">
        <img class="gallery-image" src="${i}" alt="${t}"/>
        </a>
        <ul class="gallery-image-info">
          <li class="image-items">
            <p class="image-info-items"><span class="image-items-text">Likes</span>${n}</p>
            <p class="image-info-items"><span class="image-items-text">Views</span>${b}</p>
            <p class="image-info-items"><span class="image-items-text">Comments</span>${w}</p>
            <p class="image-info-items"><span class="image-items-text">Downloads</span>${I}</p>
          </li>
        </ul>
      </li>`).join("");s.insertAdjacentHTML("beforeend",o)}function c(r,s,o){P.info({position:"topRight",message:r,iconUrl:o,messageColor:"#ffffff",backgroundColor:s,messageSize:16,layout:2,maxWidth:380,theme:"dark"})}const x="/goit-js-hw-12/assets/error-3e5cbc60.svg",S=new q(".gallery-list a",{captionsData:"alt",captionDelay:250}),m=document.querySelector(".loading"),l=document.querySelector(".form-container div"),p=document.querySelector("input"),u=document.querySelector("form"),a=document.querySelector(".load-more-img"),g=document.querySelector(".gallery-list");let d=1,f;a.classList.add("hidden");u.addEventListener("submit",$);async function $(r){if(r.preventDefault(),d=1,f=p.value,g.innerHTML="",a.classList.add("hidden"),p.value.trim()===""){a.classList.add("hidden"),c("Sorry, input is emty. Please try again!","#FFA000");return}l.classList.add("loader");try{const s=await L(d,f);if(s.total===0){c("Sorry, there are no images matching your search query. Please try again!","#EF4040",x),l.classList.remove("loader"),a.classList.add("hidden"),u.reset();return}v(s.hits,g),l.classList.remove("loader"),a.classList.remove("hidden"),S.refresh()}catch{c("Something went wrong.Please try later")}u.reset()}a.addEventListener("click",M);async function M(){d+=1,m.classList.add("loader"),a.classList.add("hidden");try{const r=await L(d,f);if(v(r.hits,g),l.classList.remove("loader"),m.classList.remove("loader"),a.classList.remove("hidden"),window.scrollBy({top:575.6666870117188,behavior:"smooth"}),r.hits.length<y)return a.classList.add("hidden"),c("We're sorry, but you've reached the end of search results.","#0071BD");S.refresh()}catch{m.classList.remove("loader"),c("You have more 100 requests per minute.Please try later")}}
//# sourceMappingURL=commonHelpers.js.map
