import{a as f,S as I,i as q}from"./assets/vendor-da186403.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const E=15;async function p(r,s){const a="https://pixabay.com/api/";f.defaults.baseURL=a;const o="42471453-a4a004408e33f852748a0909e",e="photo",t="horizontal",n=!0;try{return(await f.get(a,{params:{page:r,per_page:E,key:o,q:s,image_type:e,orientation:t,safesearch:n}})).data}catch(c){console.log(c)}}const w="/goit-js-hw-12/assets/error-3e5cbc60.svg";function h(r,s){const a=r.map(({webformatURL:o,largeImageURL:e,tags:t,likes:n,views:c,comments:b,downloads:x})=>`<li class="image-search">
        <a href="${e}">
        <img class="gallery-image" src="${o}" alt="${t}"/>
        </a>
        <ul class="gallery-image-info">
          <li class="image-items">
            <p class="image-info-items"><span class="image-items-text">Likes</span>${n}</p>
            <p class="image-info-items"><span class="image-items-text">Views</span>${c}</p>
            <p class="image-info-items"><span class="image-items-text">Comments</span>${b}</p>
            <p class="image-info-items"><span class="image-items-text">Downloads</span>${x}</p>
          </li>
        </ul>
      </li>`).join("");s.insertAdjacentHTML("beforeend",a)}function y(){new I(".gallery-list a",{captionsData:"alt",captionDelay:250}).refresh()}function d(r){q.error({position:"topRight",message:r,iconUrl:w,messageColor:"#ffffff",backgroundColor:"#EF4040",messageSize:16,layout:2,maxWidth:380,theme:"dark"})}const L=document.querySelector(".loading"),v=document.querySelector("input"),S=document.querySelector("form"),i=document.querySelector(".load-more-img"),l=document.querySelector(".form-container div"),m=document.querySelector(".gallery-list");let u=1,g;i.classList.add("hidden");S.addEventListener("submit",P);function P(r){if(r.preventDefault(),g=v.value,m.innerHTML="",v.value.trim()===""){i.classList.add("hidden"),d("Sorry, input is emty. Please try again!");return}l.classList.add("loader"),p(u,g).then(s=>{if(s.total===0){d("Sorry, there are no images matching your search query. Please try again!"),l.classList.remove("loader"),i.classList.add("hidden");return}h(s.hits,m),l.classList.remove("loader"),i.classList.remove("hidden"),i.addEventListener("click",a);function a(){L.classList.add("loader"),i.classList.add("hidden"),u+=1,p(u,g).then(o=>{if(h(o.hits,m),l.classList.remove("loader"),L.classList.remove("loader"),i.classList.remove("hidden"),o.hits.length<15)return i.classList.add("hidden"),d("We're sorry, but you've reached the end of search results.");y()})}y()}),S.reset()}
//# sourceMappingURL=commonHelpers.js.map
