import{S as x,i as I,a as p}from"./assets/vendor-da186403.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const E="/goit-js-hw-12/assets/error-3e5cbc60.svg";function f(r,s){const o=r.map(({webformatURL:a,largeImageURL:e,tags:t,likes:n,views:d,comments:b,downloads:q})=>`<li class="image-search">
        <a href="${e}">
        <img class="gallery-image" src="${a}" alt="${t}"/>
        </a>
        <ul class="gallery-image-info">
          <li class="image-items">
            <p class="image-info-items"><span class="image-items-text">Likes</span>${n}</p>
            <p class="image-info-items"><span class="image-items-text">Views</span>${d}</p>
            <p class="image-info-items"><span class="image-items-text">Comments</span>${b}</p>
            <p class="image-info-items"><span class="image-items-text">Downloads</span>${q}</p>
          </li>
        </ul>
      </li>`).join("");s.insertAdjacentHTML("beforeend",o)}function h(){new x(".gallery-list a",{captionsData:"alt",captionDelay:250}).refresh()}function l(r){I.error({position:"topRight",message:r,iconUrl:E,messageColor:"#ffffff",backgroundColor:"#EF4040",messageSize:16,layout:2,maxWidth:380,theme:"dark"})}const P=15;async function y(r,s){const o="https://pixabay.com/api/";p.defaults.baseURL=o;const a="42471453-a4a004408e33f852748a0909e",e="photo",t="horizontal",n=!0;try{return(await p.get(o,{params:{page:r,per_page:P,key:a,q:s,image_type:e,orientation:t,safesearch:n}})).data}catch{l("You have more 100 requests per minute.Please restart page")}}const L=document.querySelector(".loading"),v=document.querySelector("input"),S=document.querySelector("form"),i=document.querySelector(".load-more-img"),c=document.querySelector(".form-container div"),m=document.querySelector(".gallery-list");let u=1,g;i.classList.add("hidden");S.addEventListener("submit",w);function w(r){if(r.preventDefault(),g=v.value,m.innerHTML="",v.value.trim()===""){i.classList.add("hidden"),l("Sorry, input is emty. Please try again!");return}c.classList.add("loader"),y(u,g).then(s=>{if(s.total===0){l("Sorry, there are no images matching your search query. Please try again!"),c.classList.remove("loader"),i.classList.add("hidden");return}f(s.hits,m),c.classList.remove("loader"),i.classList.remove("hidden"),i.addEventListener("click",o);function o(){L.classList.add("loader"),i.classList.add("hidden"),u+=1,y(u,g).then(a=>{if(f(a.hits,m),c.classList.remove("loader"),L.classList.remove("loader"),i.classList.remove("hidden"),a.hits.length<15)return i.classList.add("hidden"),l("We're sorry, but you've reached the end of search results.");h()})}h()}),S.reset()}
//# sourceMappingURL=commonHelpers.js.map
